=== SugusGamberra/AprendiendoXML/5. Ejemplo Universidad/universidad.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualidied">
    <xs:element name="Universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Estudiante" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3"/>
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"/>
                                        <xs:maxInlusive value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Programa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Correo" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._-]+@[a-zA-Z0-9]+.[a-z]{2,3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SugusGamberra/AprendiendoXML/5. Ejemplo Universidad/universidad.xml
<?xml version="1.0" encoding="UTF-8"?>

<Universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="universidad.xsd">

    <Estudiante id="estudiante1">
        <Nombre>Mario Duraznos</Nombre>
        <Edad>33</Edad>
        <Programa>Ingeniería de Sistemas</Programa>
        <Correo>ma-rv.du-lut93@gmail.com</Correo>
    </Estudiante>
    <Estudiante id="estudiante2">
        <Nombre>Patricia Galopera</Nombre>
        <Edad>33</Edad>
        <Programa>Ingeniería de Redes</Programa>
        <Correo>pagalo_93@gmail.com</Correo>
    </Estudiante>
    <Estudiante id="estudiante3">
        <Nombre>Zagara Rupia</Nombre>
        <Edad>18</Edad>
        <Programa>Ingeniería de Ladridos</Programa>
        <Correo>zagarrupia2020@gmail.com</Correo>
    </Estudiante>

</Universidad>
